# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f4a831a0fa1f5062b3f957d9efe9eeb966104d3287bd390989a2d4a7c3d4c57258abbef843e91fc43556f75eaea56de48282485eba846121fc852c48bf44e5

test:
  secret_key_base: b5735f526d8b7e75279b7eaece5a89d1eca0eb1fbea2c59c56b3cef68a0defa2de4e2c67839574c3e728ad667f006b2bb026b768a77bb9d1eedcf2ead50d5ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
